let Inverters = [
  {
    make: "ENPHASE",
    type: "micro",
    breakerSize: 20,
    numMods: 1,
    label: "IQ7",
    value: "IQ7-72-2-US",
    maxInputVoltage: 48,
    mppVoltage: "27 - 37",
    maxSCCurrent: 15,
    nomACVoltage: 240,
    maxACCurrent: 1,
    nomACPower: 240,
    maxUnits: 16,
    datasheet:
      "https://jduvknlsddjuuzjmwpzo.supabase.co/storage/v1/object/public/static-files/datasheets/enphase-inverters/iq7.png",
  },
  {
    make: "ENPHASE",
    type: "micro",
    breakerSize: 20,
    numMods: 1,
    label: "IQ7+",
    value: "IQ7PLUS-72-2-US",
    maxInputVoltage: 60,
    mppVoltage: "27 - 45",
    maxSCCurrent: 15,
    nomACVoltage: 240,
    maxACCurrent: 1.21,
    nomACPower: 290,
    maxUnits: 13,
    datasheet:
      "https://jduvknlsddjuuzjmwpzo.supabase.co/storage/v1/object/public/static-files/datasheets/enphase-inverters/iq7+.png",
  },
  {
    make: "ENPHASE",
    type: "micro",
    breakerSize: 20,
    numMods: 1,
    label: "IQ7+(208V)",
    value: "IQ7PLUS-72-2-US",
    maxInputVoltage: 60,
    mppVoltage: "27 - 45",
    maxSCCurrent: 15,
    nomACVoltage: 208,
    maxACCurrent: 1.39,
    nomACPower: 290,
    maxUnits: 11,
    datasheet:
      "https://jduvknlsddjuuzjmwpzo.supabase.co/storage/v1/object/public/static-files/datasheets/enphase-inverters/iq7+.png",
  },
  {
    make: "ENPHASE",
    type: "micro",
    breakerSize: 20,
    numMods: 1,
    label: "IQ8H-3P-72-E-US(208V)",
    value: "IQ8H-3P-72-E-US",
    maxInputVoltage: 63,
    mppVoltage: "28.5 - 45",
    maxSCCurrent: 25,
    nomACVoltage: 208,
    maxACCurrent: 1.06,
    nomACPower: 380,
    maxUnits: 15,
    datasheet:
      "https://jduvknlsddjuuzjmwpzo.supabase.co/storage/v1/object/public/static-files/datasheets/enphase-inverters/iq8-3p-h.png",
  },
  {
    make: "ENPHASE",
    type: "micro",
    breakerSize: 20,
    numMods: 1,
    label: "IQ7A",
    value: "IQ7A-72-2-US",
    maxInputVoltage: 58,
    mppVoltage: "18 - 58",
    maxSCCurrent: 15,
    nomACVoltage: 240,
    maxACCurrent: 1.4,
    nomACPower: 349,
    maxUnits: 11,
    datasheet:
      "https://jduvknlsddjuuzjmwpzo.supabase.co/storage/v1/object/public/static-files/datasheets/enphase-inverters/iq7a.png",
  },
  {
    make: "ENPHASE",
    type: "micro",
    breakerSize: 20,
    numMods: 1,
    label: "IQ6",
    value: "IQ6-72-2-US",
    maxInputVoltage: 48,
    mppVoltage: "27 - 37",
    maxSCCurrent: 15,
    nomACVoltage: 240,
    maxACCurrent: 0.96,
    nomACPower: 230,
    maxUnits: 16,
    datasheet:
      "https://jduvknlsddjuuzjmwpzo.supabase.co/storage/v1/object/public/static-files/datasheets/enphase-inverters/iq6.png",
  },
  {
    make: "ENPHASE",
    type: "micro",
    breakerSize: 20,
    numMods: 1,
    label: "IQ8",
    value: "IQ8-72-2-US",
    maxInputVoltage: 50,
    mppVoltage: "27 - 37",
    maxSCCurrent: 15,
    nomACVoltage: 240,
    maxACCurrent: 1,
    nomACPower: 240,
    maxUnits: 16,
    datasheet: [
      "https://jduvknlsddjuuzjmwpzo.supabase.co/storage/v1/object/public/static-files/datasheets/enphase-inverters/iq8.png",
      "https://jduvknlsddjuuzjmwpzo.supabase.co/storage/v1/object/public/static-files/datasheets/enphase-inverters/combiner-5c.png",
    ],
  },
  {
    make: "ENPHASE",
    type: "micro",
    breakerSize: 20,
    numMods: 1,
    label: "IQ8+",
    value: "IQ8PLUS-72-2-US",
    maxInputVoltage: 60,
    mppVoltage: "29 - 45",
    maxSCCurrent: 15,
    nomACVoltage: 240,
    maxACCurrent: 1.21,
    nomACPower: 290,
    maxUnits: 13,
    datasheet: [
      "https://jduvknlsddjuuzjmwpzo.supabase.co/storage/v1/object/public/static-files/datasheets/enphase-inverters/iq8+.png",
      "https://jduvknlsddjuuzjmwpzo.supabase.co/storage/v1/object/public/static-files/datasheets/enphase-inverters/combiner-5c.png",
    ],
  },
  {
    make: "ENPHASE",
    type: "micro",
    breakerSize: 20,
    numMods: 1,
    label: "IQ8+*",
    value: "IQ8PLUS-72-2-US*",
    maxInputVoltage: 60,
    mppVoltage: "29 - 45",
    maxSCCurrent: 15,
    nomACVoltage: 240,
    maxACCurrent: 1.6,
    nomACPower: 290,
    maxUnits: 10,
    datasheet: [
      "https://jduvknlsddjuuzjmwpzo.supabase.co/storage/v1/object/public/static-files/datasheets/enphase-inverters/iq8+.png",
      "https://jduvknlsddjuuzjmwpzo.supabase.co/storage/v1/object/public/static-files/datasheets/enphase-inverters/combiner-5c.png",
    ],
  },
  {
    make: "ENPHASE",
    type: "micro",
    breakerSize: 20,
    numMods: 1,
    label: "IQ8+(M)",
    value: "IQ8PLUS-72-M-US",
    maxInputVoltage: 60,
    mppVoltage: "29 - 45",
    maxSCCurrent: 15,
    nomACVoltage: 240,
    maxACCurrent: 1.21,
    nomACPower: 290,
    maxUnits: 13,
    datasheet: [
      "https://jduvknlsddjuuzjmwpzo.supabase.co/storage/v1/object/public/static-files/datasheets/enphase-inverters/iq8+m.png",
      "https://jduvknlsddjuuzjmwpzo.supabase.co/storage/v1/object/public/static-files/datasheets/enphase-inverters/combiner-5c.png",
    ],
  },
  {
    make: "ENPHASE",
    type: "micro",
    breakerSize: 20,
    numMods: 1,
    label: "IQ8M",
    value: "IQ8M-72-2-US",
    maxInputVoltage: 60,
    mppVoltage: "33 - 45",
    maxSCCurrent: 15,
    nomACVoltage: 240,
    maxACCurrent: 1.35,
    nomACPower: 325,
    maxUnits: 11,
    datasheet: [
      "https://jduvknlsddjuuzjmwpzo.supabase.co/storage/v1/object/public/static-files/datasheets/enphase-inverters/iq8m.png",
      "https://jduvknlsddjuuzjmwpzo.supabase.co/storage/v1/object/public/static-files/datasheets/enphase-inverters/combiner-5c.png",
    ],
  },
  {
    make: "ENPHASE",
    type: "micro",
    breakerSize: 20,
    numMods: 1,
    label: "IQ8A",
    value: "IQ8A-72-2-US",
    maxInputVoltage: 60,
    mppVoltage: "36 - 45",
    maxSCCurrent: 15,
    nomACVoltage: 240,
    maxACCurrent: 1.45,
    nomACPower: 349,
    maxUnits: 11,
    datasheet: [
      "https://jduvknlsddjuuzjmwpzo.supabase.co/storage/v1/object/public/static-files/datasheets/enphase-inverters/iq8a.png",
      "https://jduvknlsddjuuzjmwpzo.supabase.co/storage/v1/object/public/static-files/datasheets/enphase-inverters/combiner-5c.png",
    ],
  },
  {
    make: "ENPHASE-SPR",
    type: "micro",
    breakerSize: 20,
    numMods: 1,
    label: "SPR-A5",
    value: "SPR-A5",
    maxInputVoltage: "59",
    mppVoltage: "38 - 43",
    maxSCCurrent: 15,
    nomACVoltage: 240,
    maxACCurrent: 1.6,
    nomACPower: 384,
    maxUnits: 10,
    datasheet: [
      "https://jduvknlsddjuuzjmwpzo.supabase.co/storage/v1/object/public/static-files/datasheets/enphase-inverters/spr-a5.png",
      "https://jduvknlsddjuuzjmwpzo.supabase.co/storage/v1/object/public/static-files/datasheets/enphase-inverters/pvs6.png",
    ],
    showCombiner: true,
  },
  {
    make: "ENPHASE",
    type: "micro",
    breakerSize: 20,
    numMods: 1,
    label: "IQ7HS-66-M-US",
    value: "IQ7HS-66-M-US",
    maxInputVoltage: "59",
    mppVoltage: "38 - 43",
    maxSCCurrent: 15,
    nomACVoltage: 240,
    maxACCurrent: 1.6,
    nomACPower: 384,
    maxUnits: 10,
    datasheet: [
      "https://jduvknlsddjuuzjmwpzo.supabase.co/storage/v1/object/public/static-files/datasheets/enphase-inverters/iq7hs.png",
    ],

  },
  {
    make: "ENPHASE-SPR",
    type: "micro",
    breakerSize: 20,
    numMods: 1,
    label: "IQ7HS-66-M-US",
    value: "IQ7HS-66-M-US",
    maxInputVoltage: "59",
    mppVoltage: "38 - 43",
    maxSCCurrent: 15,
    nomACVoltage: 240,
    maxACCurrent: 1.6,
    nomACPower: 384,
    maxUnits: 10,
    datasheet: [
      "https://jduvknlsddjuuzjmwpzo.supabase.co/storage/v1/object/public/static-files/datasheets/enphase-inverters/iq7hs.png",
      "https://jduvknlsddjuuzjmwpzo.supabase.co/storage/v1/object/public/static-files/datasheets/enphase-inverters/pvs6.png",
    ],
    showCombiner: true,
  },
  {
    make: "ENPHASE-M",
    type: "micro",
    breakerSize: 20,
    numMods: 1,
    label: "M250",
    value: "M250",
    maxInputVoltage: 48,
    mppVoltage: "27 - 39",
    maxSCCurrent: "15",
    nomACVoltage: 240,
    maxACCurrent: "1",
    nomACPower: "240",
    maxUnits: 16,
    datasheet:
      "https://jduvknlsddjuuzjmwpzo.supabase.co/storage/v1/object/public/static-files/datasheets/enphase-inverters/m250.png",
  },
  {
    make: "ENPHASE",
    type: "micro",
    breakerSize: 20,
    numMods: 1,
    label: "IQ8HC-72-M-DOM-US",
    value: "IQ8HC-72-M-DOM-US",
    maxInputVoltage: 60,
    mppVoltage: "18 - 58",
    maxSCCurrent: "25",
    nomACVoltage: 240,
    maxACCurrent: "1.58",
    nomACPower: "240",
    maxUnits: 10,
    datasheet:
      "https://jduvknlsddjuuzjmwpzo.supabase.co/storage/v1/object/public/static-files/datasheets/enphase-inverters/iq8hc.png",
  },
  {
    make: "ENPHASE",
    type: "micro",
    breakerSize: 20,
    numMods: 1,
    label: "IQ8H-3P-72-E-US",
    value: "IQ8H-3P-72-E-US",
    maxInputVoltage: 63,
    mppVoltage: "18 - 58",
    maxSCCurrent: 25,
    nomACVoltage: 208,
    maxACCurrent: 1.05,
    nomACPower: 380,
    maxUnits: 15,
    datasheet:
      "https://jduvknlsddjuuzjmwpzo.supabase.co/storage/v1/object/public/static-files/datasheets/enphase-inverters/iq8-3p-h.png",
    showCombiner: true,
  },
  {
    make: "ENPHASE",
    type: "micro",
    breakerSize: 20,
    numMods: 1,
    label: "IQ8X-80-M-US",
    value: "IQ8X-80-M-US",
    maxInputVoltage: 79.5,
    mppVoltage: "25 - 79.5",
    maxSCCurrent: 16,
    nomACVoltage: 240,
    maxACCurrent: 1.58,
    nomACPower: 380,
    maxUnits: 10,
    datasheet:
      "https://jduvknlsddjuuzjmwpzo.supabase.co/storage/v1/object/public/static-files/datasheets/enphase-inverters/iq8x.png",
    showCombiner: true,
  },


  {
    make: "AP-SYSTEMS",
    type: "micro",
    breakerSize: 30,
    numMods: 2,
    label: "DS3-L",
    value: "DS3-L",
    maxInputVoltage: 60,
    mppVoltage: "28 - 45",
    maxSCCurrent: "18",
    nomACVoltage: 240,
    maxACCurrent: "3.2",
    nomACPower: "768",
    maxUnits: 7,
    datasheet:
      "https://jduvknlsddjuuzjmwpzo.supabase.co/storage/v1/object/public/static-files/datasheets/apsys-inverters/ds3l.png",
    showCombiner: true,
  },
  {
    make: "HOYMILES",
    type: "micro",
    breakerSize: 30,
    numMods: 1,
    label: "HMS-400",
    value: "HMS-400",
    maxInputVoltage: 65,
    mppVoltage: "16 - 60",
    maxSCCurrent: "14",
    nomACVoltage: 240,
    maxACCurrent: "1.5",
    nomACPower: "360",
    maxUnits: 16,
    datasheet:
      "https://jduvknlsddjuuzjmwpzo.supabase.co/storage/v1/object/public/static-files/datasheets/hoymiles-inverters/hms-400.png",
    showCombiner: true,
  },
  {
    make: "HOYMILES",
    type: "micro",
    breakerSize: 30,
    numMods: 2,
    label: "HMS-700",
    value: "HMS-700",
    maxInputVoltage: 60,
    mppVoltage: "16 - 60",
    maxSCCurrent: "11.5",
    nomACVoltage: 240,
    maxACCurrent: "2.66",
    nomACPower: "638",
    maxUnits: 9,
    datasheet:
      "https://jduvknlsddjuuzjmwpzo.supabase.co/storage/v1/object/public/static-files/datasheets/hoymiles-inverters/hms-700.png",
    altInverter: "HMS-400",
    showCombiner: true,
  },
  {
    make: "HOYMILES",
    type: "micro",
    breakerSize: 30,
    numMods: 4,
    label: "HM-1200NT",
    value: "HM-1200NT",
    maxInputVoltage: 60,
    mppVoltage: "16 - 60",
    maxSCCurrent: "11.5",
    nomACVoltage: 240,
    maxACCurrent: "5",
    nomACPower: "1200",
    maxUnits: 4,
    datasheet:
      "https://jduvknlsddjuuzjmwpzo.supabase.co/storage/v1/object/public/static-files/datasheets/hoymiles-inverters/hm-1200.png",
    altInverter: "HM-600NT",
    showCombiner: true,
  },
  {
    make: "HOYMILES",
    type: "micro",
    breakerSize: 30,
    numMods: 4,
    label: "HM-1500NT",
    value: "HM-1500NT",
    maxInputVoltage: 60,
    mppVoltage: "16 - 60",
    maxSCCurrent: "11.5",
    nomACVoltage: 240,
    maxACCurrent: "5.99",
    nomACPower: "1438",
    maxUnits: 4,
    datasheet:
      "https://jduvknlsddjuuzjmwpzo.supabase.co/storage/v1/object/public/static-files/datasheets/hoymiles-inverters/hm-1200.png",
    altInverter: "HM-700NT",
    showCombiner: true,
  },
  {
    make: "HOYMILES",
    type: "micro",
    breakerSize: 30,
    numMods: 2,
    label: "HM-600NT",
    value: "HM-600NT",
    maxInputVoltage: 60,
    mppVoltage: "16 - 60",
    maxSCCurrent: "11.5",
    nomACVoltage: 240,
    maxACCurrent: "2.46",
    nomACPower: "590",
    maxUnits: 9,
    datasheet:
      "https://jduvknlsddjuuzjmwpzo.supabase.co/storage/v1/object/public/static-files/datasheets/hoymiles-inverters/hm-600.png",
    showCombiner: true,
  },
  {
    make: "HOYMILES",
    type: "micro",
    breakerSize: 30,
    numMods: 2,
    label: "HM-700NT",
    value: "HM-700NT",
    maxInputVoltage: 60,
    mppVoltage: "16 - 60",
    maxSCCurrent: "11.5",
    nomACVoltage: 240,
    maxACCurrent: "2.66",
    nomACPower: "638",
    maxUnits: 9,
    datasheet:
      "https://jduvknlsddjuuzjmwpzo.supabase.co/storage/v1/object/public/static-files/datasheets/hoymiles-inverters/hm-600.png",
    showCombiner: true,
  },
  {
    make: "HOYMILES",
    type: "micro",
    breakerSize: 30,
    numMods: 4,
    label: "HMS-1600-4T-NA",
    value: "HMS-1600-4T-NA",
    maxInputVoltage: 60,
    mppVoltage: "16 - 60",
    maxSCCurrent: "25",
    nomACVoltage: 240,
    maxACCurrent: 6,
    nomACPower: "1440",
    maxUnits: 4,
    datasheet:
      "https://jduvknlsddjuuzjmwpzo.supabase.co/storage/v1/object/public/static-files/datasheets/hoymiles-inverters/hms-1600-4t.png",
    altInverter: "HMS-700-2T-NA",
    showCombiner: true,
  },
  {
    make: "HOYMILES",
    type: "micro",
    breakerSize: 30,
    numMods: 2,
    label: "HMS-700-2T-NA",
    value: "HMS-700-2T-NA",
    maxInputVoltage: 60,
    mppVoltage: "16 - 60",
    maxSCCurrent: "11.5",
    nomACVoltage: 240,
    maxACCurrent: "3.04",
    nomACPower: "700",
    maxUnits: 10,
    datasheet:
      "https://jduvknlsddjuuzjmwpzo.supabase.co/storage/v1/object/public/static-files/datasheets/hoymiles-inverters/hms-700.png",
    showCombiner: true,
  },
  {
    make: "NEP",
    type: "micro",
    breakerSize: 30,
    numMods: 2,
    label: "BDM-800",
    value: "BDM-800",
    maxInputVoltage: 60,
    mppVoltage: "22 - 55",
    maxSCCurrent: "20",
    nomACVoltage: 240,
    maxACCurrent: "3.2",
    nomACPower: "768",
    maxUnits: 7,
    datasheet:
      "https://jduvknlsddjuuzjmwpzo.supabase.co/storage/v1/object/public/static-files/datasheets/nep-inverters/bdm-800.png",
    altInverter: "BDM-500",
  },
  {
    make: "NEP",
    type: "micro",
    breakerSize: 30,
    numMods: 1,
    label: "BDM-500",
    value: "BDM-500",
    maxInputVoltage: 60,
    mppVoltage: "22 - 55",
    maxSCCurrent: 25,
    nomACVoltage: 240,
    maxACCurrent: "2",
    nomACPower: "500",
    maxUnits: 12,
    datasheet:
      "https://jduvknlsddjuuzjmwpzo.supabase.co/storage/v1/object/public/static-files/datasheets/nep-inverters/bdm-500.png",
  },
  {
    make: "DURACELL",
    type: "micro",
    breakerSize: 30,
    numMods: 2,
    label: "D700-M2",
    value: "D700-M2",
    maxInputVoltage: 60,
    mppVoltage: "16-60",
    maxSCCurrent: 15,
    nomACVoltage: 240,
    maxACCurrent: "2.9",
    nomACPower: "696",
    maxUnits: 8,
    datasheet:
      "https://jduvknlsddjuuzjmwpzo.supabase.co/storage/v1/object/public/static-files/datasheets/duracell-inverters/d700-m2.png",
    altInverter: "D350-M1",
  },
  {
    make: "DURACELL",
    type: "micro",
    breakerSize: 30,
    numMods: 1,
    label: "D350-M1",
    value: "D350-M1",
    maxInputVoltage: 60,
    mppVoltage: "16-60",
    maxSCCurrent: 15,
    nomACVoltage: 240,
    maxACCurrent: "1.45",
    nomACPower: "349",
    maxUnits: 8,
    datasheet:
      "https://jduvknlsddjuuzjmwpzo.supabase.co/storage/v1/object/public/static-files/datasheets/duracell-inverters/d350-m1.png",
  },
  {
    make: "CHILICON",
    type: "micro",
    breakerSize: 30,
    numMods: 2,
    label: "CP-720",
    value: "CP-720",
    maxInputVoltage: "120",
    mppVoltage: "56-82",
    maxSCCurrent: "16",
    nomACVoltage: 240,
    maxACCurrent: "3",
    nomACPower: "720",
    maxUnits: 8,
    datasheet:
      "https://jduvknlsddjuuzjmwpzo.supabase.co/storage/v1/object/public/static-files/datasheets/chilicon-inverters/cp-720.png",
    altInverter: "CP-250",
  },
  {
    make: "CHILICON",
    type: "micro",
    breakerSize: 30,
    numMods: 1,
    label: "CP-250",
    value: "CP-250",
    maxInputVoltage: "60",
    mppVoltage: "26-41",
    maxSCCurrent: "16",
    nomACVoltage: 240,
    maxACCurrent: "1.2",
    nomACPower: "289",
    maxUnits: 20,
    datasheet:
      "https://jduvknlsddjuuzjmwpzo.supabase.co/storage/v1/object/public/static-files/datasheets/chilicon-inverters/cp-250.png",
  },
  {
    make: "SOLAREDGE",
    minPanels: 8,
    type: "string",
    label: "SE3000H-US",
    value: "SE3000H-US",
    maxInputPower: "4650",
    maxInputVoltage: "480",
    nomInputVoltage: "380",
    maxInputCurrent: "8.5",
    nomACVoltage: 240,
    maxACCurrent: "12.5",
    nomACPower: "3000",
    mppts: [1, 1],
    mpptCurrent: [20, 20],
    maxStrings: 2,
    illustration:
      "https://jduvknlsddjuuzjmwpzo.supabase.co/storage/v1/object/public/static-files/elec-diagrams/string-inverter-mppt-2.svg",
    datasheet:
      "https://jduvknlsddjuuzjmwpzo.supabase.co/storage/v1/object/public/static-files/datasheets/solaredge-inverters/se3000h-us.png",
  },
  {
    make: "SOLAREDGE",
    minPanels: 8,
    type: "string",
    label: "SE3800H-US",
    value: "SE3800H-US",
    maxInputPower: "5900",
    maxInputVoltage: "480",
    nomInputVoltage: "380",
    maxInputCurrent: "10.5",
    nomACVoltage: 240,
    maxACCurrent: "16",
    nomACPower: "3800",
    mppts: [1, 1],
    mpptCurrent: [20, 20],
    maxStrings: 2,
    illustration:
      "https://jduvknlsddjuuzjmwpzo.supabase.co/storage/v1/object/public/static-files/elec-diagrams/string-inverter-mppt-2.svg",
    datasheet:
      "https://jduvknlsddjuuzjmwpzo.supabase.co/storage/v1/object/public/static-files/datasheets/solaredge-inverters/se3800h-us.png",
  },
  {
    make: "SOLAREDGE",
    minPanels: 8,
    type: "string",
    label: "SE5000H-US",
    value: "SE5000H-US",
    maxInputPower: "7750",
    maxInputVoltage: "480",
    nomInputVoltage: "380",
    maxInputCurrent: "13.5",
    nomACVoltage: 240,
    maxACCurrent: "21",
    nomACPower: "5000",
    mppts: [1, 1],
    mpptCurrent: [20, 20],
    maxStrings: 2,
    illustration:
      "https://jduvknlsddjuuzjmwpzo.supabase.co/storage/v1/object/public/static-files/elec-diagrams/string-inverter-mppt-2.svg",
    datasheet:
      "https://jduvknlsddjuuzjmwpzo.supabase.co/storage/v1/object/public/static-files/datasheets/solaredge-inverters/se5000h-us.png",
  },
  {
    make: "SOLAREDGE",
    minPanels: 8,
    type: "string",
    label: "SE6000H-US",
    value: "SE6000H-US",
    maxInputPower: "9300",
    maxInputVoltage: "480",
    nomInputVoltage: "380",
    maxInputCurrent: "16.5",
    nomACVoltage: 240,
    maxACCurrent: 25,
    nomACPower: "6000",
    mppts: [1, 1],
    mpptCurrent: [20, 20],
    maxStrings: 2,
    illustration:
      "https://jduvknlsddjuuzjmwpzo.supabase.co/storage/v1/object/public/static-files/elec-diagrams/string-inverter-mppt-2.svg",
    datasheet:
      "https://jduvknlsddjuuzjmwpzo.supabase.co/storage/v1/object/public/static-files/datasheets/solaredge-inverters/se6000h-us.png",
  },
  {
    make: "SOLAREDGE",
    minPanels: 8,
    type: "string",
    label: "SE7600H-US",
    value: "SE7600H-US",
    maxInputPower: "11800",
    maxInputVoltage: "480",
    nomInputVoltage: "400",
    maxInputCurrent: "20",
    nomACVoltage: 240,
    maxACCurrent: "32",
    nomACPower: "7600",
    maxStrings: 3,
    mppts: [1, 1, 1],
    mpptCurrent: [20, 20, 20],
    illustration:
      "https://jduvknlsddjuuzjmwpzo.supabase.co/storage/v1/object/public/static-files/elec-diagrams/string-inverter-mppt-3.svg",
    datasheet:
      "https://jduvknlsddjuuzjmwpzo.supabase.co/storage/v1/object/public/static-files/datasheets/solaredge-inverters/se7600h-us.png",
  },
  {
    make: "SOLAREDGE",
    minPanels: 8,
    type: "string",
    label: "SE10000H-US",
    value: "SE10000H-US",
    maxInputPower: "15500",
    maxInputVoltage: "480",
    nomInputVoltage: "400",
    maxInputCurrent: "27",
    nomACVoltage: 240,
    maxACCurrent: "42",
    nomACPower: 10000,
    maxStrings: 3,
    mppts: [1, 1, 1],
    mpptCurrent: [20, 20, 20],
    illustration:
      "https://jduvknlsddjuuzjmwpzo.supabase.co/storage/v1/object/public/static-files/elec-diagrams/string-inverter-mppt-3.svg",
    datasheet:
      "https://jduvknlsddjuuzjmwpzo.supabase.co/storage/v1/object/public/static-files/datasheets/solaredge-inverters/se10000h-us.png",
  },
  {
    make: "SOLAREDGE",
    minPanels: 8,
    type: "string",
    label: "SE11400H-US",
    value: "SE11400H-US",
    maxInputPower: 17650,
    maxInputVoltage: 480,
    nomInputVoltage: 400,
    maxInputCurrent: 30.5,
    nomACVoltage: 240,
    maxACCurrent: 47.5,
    nomACPower: 11400,
    maxStrings: 3,
    mppts: [1, 1, 1],
    mpptCurrent: [20, 20, 20],
    illustration:
      "https://jduvknlsddjuuzjmwpzo.supabase.co/storage/v1/object/public/static-files/elec-diagrams/string-inverter-mppt-3.svg",
    datasheet:
      "https://jduvknlsddjuuzjmwpzo.supabase.co/storage/v1/object/public/static-files/datasheets/solaredge-inverters/se11400h-us.png",
  },
  {
    make: "SOLAREDGE",
    minPanels: 8,
    type: "string",
    label: "USE3800H-USMNBL75",
    value: "USE3800H-USMNBL75",
    maxInputPower: 7600,
    maxInputVoltage: 480,
    nomInputVoltage: 380,
    maxInputCurrent: 20,
    nomACVoltage: 240,
    maxACCurrent: 16,
    nomACPower: 3800,
    mppts: [1, 1, 1],
    mpptCurrent: [40, 40, 40],
    maxStrings: 3,
    illustration:
      "https://jduvknlsddjuuzjmwpzo.supabase.co/storage/v1/object/public/static-files/elec-diagrams/string-inverter-mppt-3.svg",
    datasheet:
      "https://jduvknlsddjuuzjmwpzo.supabase.co/storage/v1/object/public/static-files/datasheets/solaredge-inverters/sehh.png",
  },
  {
    make: "SOLAREDGE",
    minPanels: 8,
    type: "string",
    label: "USE5700H-USMNBL75",
    value: "USE5700H-USMNBL75",
    maxInputPower: 15200,
    maxInputVoltage: 480,
    nomInputVoltage: 380,
    maxInputCurrent: 30,
    nomACVoltage: 240,
    maxACCurrent: 21,
    nomACPower: 5760,
    mppts: [1, 1, 1],
    mpptCurrent: [40, 40, 40],
    maxStrings: 3,
    illustration:
      "https://jduvknlsddjuuzjmwpzo.supabase.co/storage/v1/object/public/static-files/elec-diagrams/string-inverter-mppt-3.svg",
    datasheet:
      "https://jduvknlsddjuuzjmwpzo.supabase.co/storage/v1/object/public/static-files/datasheets/solaredge-inverters/sehh.png",
  },
  {
    make: "SOLAREDGE",
    minPanels: 8,
    type: "string",
    label: "USE7600H-USMNBL75",
    value: "USE7600H-USMNBL75",
    maxInputPower: 15200,
    maxInputVoltage: 480,
    nomInputVoltage: 380,
    maxInputCurrent: 40,
    nomACVoltage: 240,
    maxACCurrent: 32,
    nomACPower: 7600,
    maxStrings: 3,
    mppts: [1, 1, 1],
    mpptCurrent: [40, 40, 40],
    illustration:
      "https://jduvknlsddjuuzjmwpzo.supabase.co/storage/v1/object/public/static-files/elec-diagrams/string-inverter-mppt-3.svg",
    datasheet:
      "https://jduvknlsddjuuzjmwpzo.supabase.co/storage/v1/object/public/static-files/datasheets/solaredge-inverters/sehh.png",
  },
  {
    make: "SOLAREDGE",
    minPanels: 8,
    type: "string",
    label: "USE10000H-USMNBL75",
    value: "USE10000H-USMNBL75",
    maxInputPower: 20000,
    maxInputVoltage: 480,
    nomInputVoltage: 380,
    maxInputCurrent: 53,
    nomACVoltage: 240,
    maxACCurrent: 42,
    nomACPower: 10000,
    maxStrings: 3,
    mppts: [1, 1, 1],
    mpptCurrent: [40, 40, 40],
    illustration:
      "https://jduvknlsddjuuzjmwpzo.supabase.co/storage/v1/object/public/static-files/elec-diagrams/string-inverter-mppt-3.svg",
    datasheet:
      "https://jduvknlsddjuuzjmwpzo.supabase.co/storage/v1/object/public/static-files/datasheets/solaredge-inverters/sehh.png",
  },
  {
    make: "SOLAREDGE",
    minPanels: 8,
    type: "string",
    label: "USE11400H-USMNBL75",
    value: "USE11400H-USMNBL75",
    maxInputPower: 22800,
    maxInputVoltage: 480,
    nomInputVoltage: 380,
    maxInputCurrent: 60,
    nomACVoltage: 240,
    maxACCurrent: 47.5,
    nomACPower: 11400,
    maxStrings: 3,
    mppts: [1, 1, 1],
    mpptCurrent: [40, 40, 40],
    illustration:
      "https://jduvknlsddjuuzjmwpzo.supabase.co/storage/v1/object/public/static-files/elec-diagrams/string-inverter-mppt-3.svg",
    datasheet:
      "https://jduvknlsddjuuzjmwpzo.supabase.co/storage/v1/object/public/static-files/datasheets/solaredge-inverters/sehh.png",
  },
  {
    make: "SOLAREDGE",
    minPanels: 8,
    type: "string",
    label: "SE10000A-US",
    value: "SE10000A-US",
    maxInputPower: 13500,
    maxInputVoltage: 500,
    nomInputVoltage: 350,
    maxInputCurrent: 30.5,
    nomACVoltage: 240,
    maxACCurrent: 42,
    nomACPower: 10000,
    maxStrings: 3,
    mppts: [1, 1, 1],
    mpptCurrent: [20, 20, 20],
    illustration:
      "https://jduvknlsddjuuzjmwpzo.supabase.co/storage/v1/object/public/static-files/elec-diagrams/string-inverter-mppt-3.svg",
    datasheet:
      "https://jduvknlsddjuuzjmwpzo.supabase.co/storage/v1/object/public/static-files/datasheets/solaredge-inverters/se10000a-us.png",
  },
  {
    make: "SOLAREDGE",
    minPanels: 8,
    type: "string",
    label: "SE7600H-US-EV",
    value: "SE7600H-US-EV",
    maxInputPower: 11800,
    maxInputVoltage: 480,
    nomInputVoltage: 400,
    maxInputCurrent: 20,
    nomACVoltage: 240,
    maxACCurrent: 32,
    nomACPower: 7600,
    maxStrings: 2,
    mppts: [1, 1],
    mpptCurrent: [20, 20],
    illustration:
      "https://jduvknlsddjuuzjmwpzo.supabase.co/storage/v1/object/public/static-files/elec-diagrams/string-inverter-mppt-2.svg",
    datasheet: [
      "https://jduvknlsddjuuzjmwpzo.supabase.co/storage/v1/object/public/static-files/datasheets/solaredge-inverters/se7600h-us-ev.png",

      "https://jduvknlsddjuuzjmwpzo.supabase.co/storage/v1/object/public/static-files/datasheets/solaredge-inverters/se7600h-us-ev-2.png",
    ],
  },
  {
    make: "GENERAC",
    type: "pika",
    label: "PWRCELL 7.6",
    value: "PWRCELL 7.6",
    maxInputPower: 11800,
    maxInputVoltage: 420,
    nomInputVoltage: 380,
    maxInputCurrent: 30,
    nomACVoltage: 240,
    maxACCurrent: 32,
    nomACPower: 7600,
    datasheet:
      "https://jduvknlsddjuuzjmwpzo.supabase.co/storage/v1/object/public/static-files/datasheets/generac-inverters/pwrcell-7600.png",
  },
  {
    make: "SOLARK",
    type: "string",
    label: "15K-2P-N",
    value: "15K-2P-N",
    maxInputPower: 19500,
    maxInputVoltage: 500,
    nomInputVoltage: 300,
    maxInputCurrent: 26,
    startVoltage: 125,
    nomACVoltage: 240,
    maxACCurrent: 62.5,
    nomACPower: 12000,
    maxStrings: 6,
    mppts: [2, 2, 2],
    mpptCurrent: [26, 26, 26],
    illustration:
      "https://jduvknlsddjuuzjmwpzo.supabase.co/storage/v1/object/public/static-files/elec-diagrams/string-inverter-mppt-3-comb.svg",
    datasheet:
      "https://jduvknlsddjuuzjmwpzo.supabase.co/storage/v1/object/public/static-files/datasheets/solark-inverters/solark-15.png",
  },
  {
    make: "EG4",
    type: "string",
    label: "18KPV-12LV",
    value: "18KPV-12LV",
    maxInputPower: "21000",
    maxInputVoltage: "600",
    nomInputVoltage: "360",
    maxInputCurrent: 25,
    startVoltage: 100,
    nomACVoltage: 240,
    maxACCurrent: 50,
    nomACPower: 12000,
    maxStrings: 4,
    mppts: [2, 1, 1],
    mpptCurrent: [25, 15, 15],
    illustration:
      "https://jduvknlsddjuuzjmwpzo.supabase.co/storage/v1/object/public/static-files/elec-diagrams/string-inverter-mppt-3-comb.svg",
    datasheet:
      "https://jduvknlsddjuuzjmwpzo.supabase.co/storage/v1/object/public/static-files/datasheets/eg4-inverters/18kpv.png",
  },
  {
    make: "EG4",
    type: "string",
    label: "12KPV",
    value: "12KPV",
    maxInputPower: "15000",
    maxInputVoltage: "600",
    nomInputVoltage: "360",
    maxInputCurrent: 25,
    startVoltage: 100,
    nomACVoltage: 240,
    maxACCurrent: 50,
    nomACPower: 12000,
    maxStrings: 4,
    mppts: [2, 2],
    mpptCurrent: [25, 25],
    illustration:
      "https://jduvknlsddjuuzjmwpzo.supabase.co/storage/v1/object/public/static-files/elec-diagrams/string-inverter-mppt-2.svg",
    datasheet:
      "https://jduvknlsddjuuzjmwpzo.supabase.co/storage/v1/object/public/static-files/datasheets/eg4-inverters/12kpv.png",
  },
  {
    make: "SUNSYNK",
    type: "string",
    label: "SYNK-5K-SG04LP1",
    value: "SYNK-5K-SG04LP1",
    maxInputPower: "6500",
    maxInputVoltage: "500",
    nomInputVoltage: "370",
    maxInputCurrent: "17",
    nomACVoltage: 220,
    maxACCurrent: 25,
    nomACPower: 5000,
    maxStrings: 2,
    mppts: [1, 1],
    mpptCurrent: [13, 13],
    illustration:
      "https://jduvknlsddjuuzjmwpzo.supabase.co/storage/v1/object/public/static-files/elec-diagrams/string-inverter-mppt-2.svg",
    datasheet:
      "https://jduvknlsddjuuzjmwpzo.supabase.co/storage/v1/object/public/static-files/datasheets/sunsynk-inverters/ss-5.png",
  },
  {
    make: "AMENSOLAR",
    type: "string",
    label: "N3H-X10-US",
    value: "N3H-X10-US",
    maxInputPower: "15000",
    maxInputVoltage: "500",
    nomInputVoltage: "370",
    maxInputCurrent: "14",
    nomACVoltage: 240,
    maxACCurrent: 45.8,
    nomACPower: 10000,
    maxStrings: 4,
    mppts: [1, 1, 1, 1],
    mpptCurrent: [14, 14, 14, 14],
    illustration:
      "https://jduvknlsddjuuzjmwpzo.supabase.co/storage/v1/object/public/static-files/elec-diagrams/string-inverter-mppt-4.svg",
    datasheet:
      "https://jduvknlsddjuuzjmwpzo.supabase.co/storage/v1/object/public/static-files/datasheets/amensolar-inverters/n3h-10.png",
  },
  {
    make: "TESLA",
    type: "string",
    label: "TESLA-1538000",
    value: "TESLA-1538000",
    maxInputPower: 7600,
    maxInputVoltage: 600,
    nomInputVoltage: 380,
    maxInputCurrent: 17,
    nomACVoltage: 240,
    maxACCurrent: 32,
    nomACPower: 7600,
    maxStrings: 4,
    startVoltage: 60,
    mppts: [1, 1, 1, 1],
    mpptCurrent: [13, 13, 13, 13],
    illustration:
      "https://jduvknlsddjuuzjmwpzo.supabase.co/storage/v1/object/public/static-files/elec-diagrams/string-inverter-mppt-4.svg",
    datasheet:
      "https://jduvknlsddjuuzjmwpzo.supabase.co/storage/v1/object/public/static-files/datasheets/tesla-inverters/tsla7600.png",
  },
  {
    make: "TESLA",
    type: "string",
    label: "TESLA-1707000",
    value: "TESLA-1707000",
    maxInputPower: 20000,
    maxInputVoltage: 600,
    nomInputVoltage: 380,
    maxInputCurrent: 15,
    nomACVoltage: 240,
    maxACCurrent: 48,
    nomACPower: 11500,
    maxStrings: 6,
    mppts: [1, 1, 1, 1, 1, 1],
    mpptCurrent: [13, 13, 13, 13, 13, 13],
    startVoltage: 60,
    illustration:
      "https://jduvknlsddjuuzjmwpzo.supabase.co/storage/v1/object/public/static-files/elec-diagrams/string-inverter-mppt-4.svg",
    datasheet:
      "https://jduvknlsddjuuzjmwpzo.supabase.co/storage/v1/object/public/static-files/datasheets/tesla-inverters/tslapowerwall3.png",
  },
  {
    make: "TESLA",
    type: "string",
    label: "TESLA-1707000-JESS",
    value: "TESLA-1707000-JESS",
    maxInputPower: 20000,
    maxInputVoltage: 600,
    nomInputVoltage: 380,
    maxInputCurrent: 15,
    nomACVoltage: 240,
    maxACCurrent: 48,
    nomACPower: 11500,
    maxStrings: 6,
    mppts: [10, 10, 10, 10, 10, 10],
    mpptCurrent: [13, 13, 13, 13, 13, 13],
    startVoltage: 60,
    illustration:
      "https://jduvknlsddjuuzjmwpzo.supabase.co/storage/v1/object/public/static-files/elec-diagrams/string-inverter-mppt-4.svg",
    datasheet:
      "https://jduvknlsddjuuzjmwpzo.supabase.co/storage/v1/object/public/static-files/datasheets/tesla-inverters/tslapowerwall3.png",
  },
  {
    make: "DELTA",
    type: "string",
    label: "M4-TL-US",
    value: "M4-TL-US",
    maxInputPower: 5184,
    maxInputVoltage: 600,
    nomInputVoltage: 380,
    maxInputCurrent: 12,
    nomACVoltage: 240,
    maxACCurrent: 16,
    nomACPower: 3840,
    maxStrings: 2,
    mppts: [2, 2],
    mpptCurrent: [15, 15],
    startVoltage: 50,
    illustration:
      "https://jduvknlsddjuuzjmwpzo.supabase.co/storage/v1/object/public/static-files/elec-diagrams/string-inverter-mppt-2.svg",
    datasheet:
      "https://jduvknlsddjuuzjmwpzo.supabase.co/storage/v1/object/public/static-files/datasheets/delta-inverters/delta-m-series.png",
  },
  {
    make: "DELTA",
    type: "string",
    label: "M5-TL-US",
    value: "M5-TL-US",
    maxInputPower: 6480,
    maxInputVoltage: 600,
    nomInputVoltage: 380,
    maxInputCurrent: 12,
    nomACVoltage: 240,
    maxACCurrent: 20,
    nomACPower: 4800,
    maxStrings: 2,
    mppts: [2, 2],
    mpptCurrent: [15, 15],
    startVoltage: 50,
    illustration:
      "https://jduvknlsddjuuzjmwpzo.supabase.co/storage/v1/object/public/static-files/elec-diagrams/string-inverter-mppt-2.svg",
    datasheet:
      "https://jduvknlsddjuuzjmwpzo.supabase.co/storage/v1/object/public/static-files/datasheets/delta-inverters/delta-m-series.png",
  },
  {
    make: "DELTA",
    type: "string",
    label: "M6-TL-US",
    value: "M6-TL-US",
    maxInputPower: 7776,
    maxInputVoltage: 600,
    nomInputVoltage: 380,
    maxInputCurrent: 12,
    nomACVoltage: 240,
    maxACCurrent: 20,
    nomACPower: 5760,
    maxStrings: 2,
    mppts: [2, 2, 2],
    mpptCurrent: [15, 15, 15],
    startVoltage: 50,
    illustration:
      "https://jduvknlsddjuuzjmwpzo.supabase.co/storage/v1/object/public/static-files/elec-diagrams/string-inverter-mppt-3.svg",
    datasheet:
      "https://jduvknlsddjuuzjmwpzo.supabase.co/storage/v1/object/public/static-files/datasheets/delta-inverters/delta-m-series.png",
  },
  {
    make: "DELTA",
    type: "string",
    label: "M8-TL-US",
    value: "M8-TL-US",
    maxInputPower: 10368,
    maxInputVoltage: 600,
    nomInputVoltage: 380,
    maxInputCurrent: 12,
    nomACVoltage: 240,
    maxACCurrent: 32,
    nomACPower: 7680,
    maxStrings: 2,
    mppts: [2, 2, 2],
    mpptCurrent: [15, 15, 15],
    startVoltage: 50,
    illustration:
      "https://jduvknlsddjuuzjmwpzo.supabase.co/storage/v1/object/public/static-files/elec-diagrams/string-inverter-mppt-3.svg",
    datasheet:
      "https://jduvknlsddjuuzjmwpzo.supabase.co/storage/v1/object/public/static-files/datasheets/delta-inverters/delta-m-series.png",
  },
  {
    make: "DELTA",
    type: "string",
    label: "M10-4-TL-US",
    value: "M10-4-TL-US",
    maxInputPower: 12960,
    maxInputVoltage: 600,
    nomInputVoltage: 380,
    maxInputCurrent: 12,
    nomACVoltage: 240,
    maxACCurrent: 40,
    nomACPower: 9600,
    maxStrings: 8,
    mppts: [2, 2, 2, 2],
    mpptCurrent: [15, 15, 15, 15],
    startVoltage: 50,
    illustration:
      "https://jduvknlsddjuuzjmwpzo.supabase.co/storage/v1/object/public/static-files/elec-diagrams/string-inverter-mppt-4.svg",
    datasheet:
      "https://jduvknlsddjuuzjmwpzo.supabase.co/storage/v1/object/public/static-files/datasheets/delta-inverters/delta-m-series.png",
  },
  {
    make: "DELTA",
    type: "string",
    label: "M10-TL-US",
    value: "M10-TL-US",
    maxInputPower: 12960,
    maxInputVoltage: 600,
    nomInputVoltage: 380,
    maxInputCurrent: 12,
    nomACVoltage: 240,
    maxACCurrent: 40,
    nomACPower: 9600,
    maxStrings: 4,
    mppts: [2, 2],
    mpptCurrent: [30, 30],
    startVoltage: 50,
    illustration:
      "https://jduvknlsddjuuzjmwpzo.supabase.co/storage/v1/object/public/static-files/elec-diagrams/string-inverter-mppt-2.svg",
    datasheet:
      "https://jduvknlsddjuuzjmwpzo.supabase.co/storage/v1/object/public/static-files/datasheets/delta-inverters/delta-m-series.png",
  },
  {
    make: "SUNGOLD",
    type: "string",
    label: "SPH10048P",
    value: "SPH10048P",
    maxInputPower: 11000,
    maxInputVoltage: 500,
    nomInputVoltage: 380,
    maxInputCurrent: 22,
    nomACVoltage: 240,
    maxACCurrent: 42,
    nomACPower: 10000,
    maxStrings: 4,
    mppts: [2, 2],
    mpptCurrent: [22, 22],
    startVoltage: 125,
    illustration:
      "https://jduvknlsddjuuzjmwpzo.supabase.co/storage/v1/object/public/static-files/elec-diagrams/string-inverter-mppt-2.svg",
    datasheet:
      "https://jduvknlsddjuuzjmwpzo.supabase.co/storage/v1/object/public/static-files/datasheets/sungold-inverters/sg-sph10.png",
  },
  {
    make: "CHINT",
    type: "string",
    label: "CPS-SCA25KTL",
    value: "CPS-SCA25KTL",
    maxInputPower: 45000,
    maxInputVoltage: 1000,
    nomInputVoltage: 660,
    maxInputCurrent: 135,
    nomACVoltage: 208,
    phases: 3,
    maxACCurrent: 69.5,
    nomACPower: 25000,
    maxStrings: 9,
    mppts: [3, 3, 3],
    mpptCurrent: [45, 45, 45],
    startVoltage: 330,
    illustration:
      "https://jduvknlsddjuuzjmwpzo.supabase.co/storage/v1/object/public/static-files/elec-diagrams/string-inverter-mppt-3.svg",
    datasheet: [
      "https://jduvknlsddjuuzjmwpzo.supabase.co/storage/v1/object/public/static-files/datasheets/chint-inverters/chint-25k.png",
      "https://jduvknlsddjuuzjmwpzo.supabase.co/storage/v1/object/public/static-files/datasheets/chint-inverters/chint-app-note.png",
    ],
  },
  {
    make: "QCELLS",
    type: "string",
    label: "QVOLT-76XS",
    value: "QVOLT-76XS",
    maxInputPower: 15200,
    maxInputVoltage: 550,
    nomInputVoltage: 360,
    maxInputCurrent: 60,
    nomACVoltage: 240,
    maxACCurrent: 31.7,
    nomACPower: 7608,
    maxStrings: 3,
    mppts: [1, 1, 1],
    mpptCurrent: [20, 20, 20],
    startVoltage: 120,
    illustration:
      "https://jduvknlsddjuuzjmwpzo.supabase.co/storage/v1/object/public/static-files/elec-diagrams/string-inverter-mppt-3.svg",
    datasheet: [
      "https://jduvknlsddjuuzjmwpzo.supabase.co/storage/v1/object/public/static-files/datasheets/qcells-inverters/qvolt-76SX.png",
    ],
  },
  {
    make: "FOX",
    type: "string",
    label: "ACI-11.4-US",
    value: "ACI-11.4-US",
    maxInputPower: 22800,
    maxInputVoltage: 600,
    nomInputVoltage: 380,
    maxInputCurrent: 44,
    nomACVoltage: 240,
    maxACCurrent: 48,
    nomACPower: 11400,
    maxStrings: 4,
    mppts: [2, 1, 1],
    mpptCurrent: [28, 14, 14],
    startVoltage: 120,
    illustration:
      "https://jduvknlsddjuuzjmwpzo.supabase.co/storage/v1/object/public/static-files/elec-diagrams/string-inverter-mppt-3.svg",
    datasheet: [
      "https://jduvknlsddjuuzjmwpzo.supabase.co/storage/v1/object/public/static-files/datasheets/fox-inverters/fox-aci.png",
    ],
  },

]

export { Inverters }
